language: python
python:
  - "3.6"

env:
  global:
    - CC_TEST_REPORTER_ID=05d0affb25f5b5843db7ac7c1e7dac3e29359b8d90ebd670e83e2f0ac8853491

install:
  - "pip install -r requirements.txt"

# command to run tests
script:
  - python3 -m pytest
  - coveralls
  - coverage run tests.py

after_success:
  - codecov