language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - "pip install -r requirements.txt"
  - "pip install psycopg2-binary"

before_script:
  - "psql -c 'create database storemanager;' -U postgres"
  - psql -c "CREATE USER andela WITH PASSWORD 'bootcamp';" -U postgres

# command to run tests
script:
  - python3 -m pytest --cov=app/
  
after_success:
  - coveralls