language: python
python:
  - "3.6"

env:
  global:
    - CODECOV_TOKEN="c949fbec-81df-4f79-8fcd-f9f15891bfce"

install:
  - "pip install -r requirements.txt"

# command to run tests
script:
  - python3 -m pytest
  - coveralls
  - coverage pytest

after_success:
  - codecov